#------------------------------------------------------------------------
# Settings
#------------------------------------------------------------------------

# Project Name
PROJ := DATA - <Library under test>

#------------------------------------------------------------------------
# Targets
#------------------------------------------------------------------------
.PHONY: all compile clean

all: compile

compile:
	# TODO: add compilation code here
	gcc prog.c -o prog

clean:
	# TODO: add cleanup target here
	rm -rf prog

help:
	@echo
	@echo "$(PROJ)"
	@echo
	@echo "  make [all] ............. Prepare and/or compile."
	@echo "  make help .............. Show this text."
	@echo "  make clean ............. Clean up."
	@echo

