name: lint

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install flake8
      - run: >
            flake8 --exclude __pycache__,.pyenv
            --max-line-length=88
            --ignore=E203,E266,E501,W503
        working-directory: analysis
      - run: >
            flake8 --exclude openssl
            --max-line-length=88
            --ignore=E203,E266,E501,W503
        working-directory: cryptolib/common
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install black
      - run: |
          black --version
          black --check --diff .
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install clang-format
      - run: |
          clang-format -style="{IndentWidth: 4}" --dry-run --Werror -i *.*
        working-directory: pintool
